name: Build and deploy to Kuroco front
on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  #for Push
  pushed_build:
    name: Build(pushed)
    if: (github.repository == 'HisashiHasebe/hasebetest-kuroco-nuxt3' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: CI Cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Generate
        run: npm run generate
      - name: Zip artifact for upload
        run: cd ./.output/public && zip ../../dist.zip . -r
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist.zip
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://hasebetest2.g.kuroco.app/direct/menu/github/"
          webhook_secret: "5323000f32ecfba4fc33545d3bcab593"
          data: '{"single_zip":"1","domain":"hasebetest2.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'
